<a href="https://colab.research.google.com/github/Lstsk/Machine-Learning-Repo/blob/main/MachineLearningFromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

inputs = [
    [1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8],
    ]

weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]


weights2 = [[0.1,-0.14,0.5],[-0.5, 0.12,-0.33],[-0.44, 0.73, -0.13]]

biases2 = [-1,2,-0.5]


'''(1*0.2 + 2*0.8 +3 *-0.5+2.5*1.0) + 2
(inputs x weights) + biase
'''
layer1_ouputs = np.dot(inputs, np.array(weights).T) + biases

layer2_ouputs = np.dot(layer1_ouputs, np.array(weights2).T) + biases2

print(layer2_ouputs)




[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [24]:
import numpy as np

X = [
    [1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8],
    ]

# define two hidden 

'''initializing weights -> random value between 1 and -1
 biases usually initialize as 
'''
np.random.seed(0)

class Layer_Desnse:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10* np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Desnse(4,5)
layer2 = Layer_Desnse(5,2)

layer1.forward(X)
print(layer1.output)
# pass layer1 output into layer2
layer2.forward(layer1.output)
print(layer2.output)


[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
